=== enmim7/Projecte2/Pagina_web/xml/curses.dtd
<!ELEMENT curses (cursa+) >
<!ELEMENT cursa (title, portada) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT portada (#PCDATA)>

<!ATTLIST cursa category CDATA #REQUIRED >

=== enmim7/Projecte2/Pagina_web/xml/curses.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curses SYSTEM "curses.dtd">
<?xml-stylesheet type="text/xsl" href="curses.xsl"?>
<curses>
  <cursa category="children">
    <title>Bicicleta</title>
    
    <portada>ciclisme.jpg</portada>
  </cursa>
  <cursa category="children">
    <title>Natació</title>
   
    <portada>natacio.jpg</portada>
  </cursa>
  <cursa category="children">
    <title>Running</title>
  
    <portada>correr.jpg</portada>
  </cursa>
  <cursa category="web">
    <title>Triatló</title>
   
    <portada>triatlo.png</portada>
  </cursa>
</curses>
