=== enmim7/Projecte2/Projecte 2/pagina_web/xml/bookstore.dtd
<!ELEMENT bookstore (book+) >
<!ELEMENT book (title, author, year , price, portada) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT author (#PCDATA) >
<!ELEMENT year (#PCDATA) >
<!ELEMENT price (#PCDATA) >
<!ELEMENT portada (#PCDATA)>

<!ATTLIST book category CDATA #REQUIRED >

=== enmim7/Projecte2/Projecte 2/pagina_web/xml/bookstore.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore SYSTEM "bookstore.dtd">
<?xml-stylesheet type="text/xsl" href="bookstore.xsl"?>
<bookstore>
  <book category="children">
    <title>Harry Potter</title>
    <author>J K. Rowling</author>
    <year>2005</year>
    <price>29.99</price>
    <portada>harry.png</portada>
  </book>
  <book category="children">
    <title>Harry Potter</title>
    <author>J K. Rowling</author>
    <year>2005</year>
    <price>29.99</price>
    <portada>harry.png</portada>
  </book>
  <book category="children">
    <title>Harry Potter</title>
    <author>J K. Rowling</author>
    <year>2005</year>
    <price>29.99</price>
    <portada>harry.png</portada>
  </book>
  <book category="web">
    <title>Learning XML</title>
    <author>Erik T. Ray</author>
    <year>2003</year>
    <price>39.95</price>
    <portada>harry.png</portada>
  </book>
</bookstore>
